feat: first time payment with credit card integration
brucruz/sagittarius pull request #134
Opened 2020-11-25 19:45 UTC by gus-messagi

https://trello.com/c/MZhhGUC8/267-criar-funcionalidade-de-transa%C3%A7%C3%A3o-com-cart%C3%A3o-de-cr%C3%A9dito

I removed Radio Group for document types, because pagarme just accepts CPF for individual customer

2020-11-25 21:33 UTC, brucruz requested changes

2020-11-25 21:33 UTC, brucruz commented on src/components/organisms/CreditCardForm.tsx
> +      amount: Number.parseInt(
why do all this, if there is a bagTotalPrice (without being formatted)?

2020-11-25 21:33 UTC, brucruz commented on src/components/organisms/CreditCardForm.tsx
> +      .connect({ api_key: process.env.NEXT_PUBLIC_PAGARME_API_KEY })
is it possible for this key not to be public?

2020-11-25 21:33 UTC, brucruz commented on src/components/organisms/CreditCardForm.tsx
> +                type: 'cpf',
cpf shouldnt be hardcode since there's the option of choosing what type of document the user want to share, right?

2020-11-25 21:33 UTC, brucruz commented on src/pages/checkout/[patientId]/pagamento.tsx
>              />
why is document selection gone?

2020-11-26 01:24 UTC, gus-messagi commented on src/components/organisms/CreditCardForm.tsx
> +      amount: Number.parseInt(
Cause in this way I'm sure that price with comma is working and is pretty much easy to work with pagarme's amount than using bagTotalPrice even if price doesn't have comma

2020-11-26 01:54 UTC, gus-messagi commented on src/components/organisms/CreditCardForm.tsx
> +      .connect({ api_key: process.env.NEXT_PUBLIC_PAGARME_API_KEY })
If not public will be available just for node env, not for the browser

2020-11-26 01:55 UTC, gus-messagi commented on src/components/organisms/CreditCardForm.tsx
> +      setIsPaymentButtonDisabled(true);
I'm not able to reproduce it, could you maybe do a video showing the flow ?

2020-11-26 01:55 UTC, gus-messagi commented on src/pages/checkout/[patientId]/pagamento.tsx
>              />
I removed Radio Group for document types, because pagarme just accepts CPF for individual customer

2020-11-26 12:39 UTC, brucruz commented on src/components/organisms/CreditCardForm.tsx
> +      setIsPaymentButtonDisabled(true);
just sent you in discord

2020-11-26 18:04 UTC, merged